export const jobsData = [
  {
    companyName: "Photosnap",
    companyLogo: "../images/photosnap.svg",
    ocupation: "Senior Frontend Developer",
    postDate: "1d ago",
    time: "Full time",
    country: "USA only",
    isNew: true,
    isFeatured: true,
    tags: ["Frontend", "Senior", "HTML", "CSS", "JavaScript"],
  },
  {
    companyName: "Manage",
    companyLogo: "../images/manage.svg",
    ocupation: "Fullstack Developer",
    postDate: "1d ago",
    time: "Part time",
    country: "Remote",
    isNew: true,
    isFeatured: true,
    tags: ["Fullstack", "Midweight", "Python", "React"],
  },
  {
    companyName: "Account",
    companyLogo: "../images/account.svg",
    ocupation: "Junior Frontend Developer",
    postDate: "2d ago",
    time: "Part time",
    country: "USA only",
    isNew: true,
    isFeatured: false,
    tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
  },
  {
    companyName: "MyHome",
    companyLogo: "../images/myhome.svg",
    ocupation: "Junior Frontend Developer",
    postDate: "5d ago",
    time: "Contract",
    country: "USA only",
    isNew: false,
    isFeatured: false,
    tags: ["Frontend", "Junior", "CSS", "JavaScript"],
  },
  {
    companyName: "Loop Studios",
    companyLogo: "../images/loop-studios.svg",
    ocupation: "Software Engineer",
    postDate: "1w ago",
    time: "Full time",
    country: "Worldwide",
    isNew: false,
    isFeatured: false,
    tags: ["Fullstack", "Midweight", "JavaScript", "Sass", "Ruby"],
  },
  {
    companyName: "FaceIt",
    companyLogo: "../images/faceit.svg",
    ocupation: "Junior Backend Developer",
    postDate: "2w ago",
    time: "Full time",
    country: "UK only",
    isNew: false,
    isFeatured: false,
    tags: ["Backend", "Junior", "Ruby", "RoR"],
  },
  {
    companyName: "Shortly",
    companyLogo: "../images/shortly.svg",
    ocupation: "Junior Developer",
    postDate: "2w ago",
    time: "Full time",
    country: "Worldwide",
    isNew: false,
    isFeatured: false,
    tags: ["Frontend", "Junior", "HTML", "Sass", "JavaScript "],
  },
  {
    companyName: "Insure",
    companyLogo: "../images/insure.svg",
    ocupation: "Junior Frontend Developer",
    postDate: "2w ago",
    time: "Full time",
    country: "USA only",
    isNew: false,
    isFeatured: false,
    tags: ["Frontend", "Junior", "Vue", "JavaScript", "Sass"],
  },
  {
    companyName: "Eyecam Co.",
    companyLogo: "../images/eyecam-co.svg",
    ocupation: "Full Stack Engineer",
    postDate: "3w ago",
    time: "Full time",
    country: "Worldwide",
    isNew: false,
    isFeatured: false,
    tags: ["Fullstack", "Midweight", "JavaScript", "Django", "Python"],
  },
  {
    companyName: "The Air Filter Company",
    companyLogo: "../images/the-air-filter-company.svg",
    ocupation: "Junior Backend Developer",
    postDate: "1mo ago",
    time: "Part time",
    country: "Worldwide",
    isNew: false,
    isFeatured: false,
    tags: ["Frontend", "Junior", "React", "Sass", "JavaScript"],
  },
];
